# Autogenerated wrapper script for Qt6WebChannel_jll for aarch64-apple-darwin
export libqt6webchannel

using Qt6Base_jll
using Qt6Declarative_jll
using Qt6WebSockets_jll
JLLWrappers.@generate_wrapper_header("Qt6WebChannel")
JLLWrappers.@declare_library_product(libqt6webchannel, "@rpath/QtWebChannel")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll, Qt6WebSockets_jll)
    JLLWrappers.@init_library_product(
        libqt6webchannel,
        "lib/QtWebChannel.framework/Versions/A/QtWebChannel",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
