# Autogenerated wrapper script for Qt6WebChannel_jll for i686-w64-mingw32-cxx03
export libqt6webchannel

using Qt6Base_jll
using Qt6Declarative_jll
using Qt6WebSockets_jll
JLLWrappers.@generate_wrapper_header("Qt6WebChannel")
JLLWrappers.@declare_library_product(libqt6webchannel, "Qt6WebChannel.dll")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll, Qt6WebSockets_jll)
    JLLWrappers.@init_library_product(
        libqt6webchannel,
        "bin\\Qt6WebChannel.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
