# Autogenerated wrapper script for Qt6WebChannel_jll for x86_64-linux-gnu-cxx11
export libqt6webchannel

using Qt6Base_jll
using Qt6Declarative_jll
using Qt6WebSockets_jll
JLLWrappers.@generate_wrapper_header("Qt6WebChannel")
JLLWrappers.@declare_library_product(libqt6webchannel, "libQt6WebChannel.so.6")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll, Qt6WebSockets_jll)
    JLLWrappers.@init_library_product(
        libqt6webchannel,
        "lib/libQt6WebChannel.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
